version: 0.2

env:
  variables:
    MyEnv: "dev"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
      
  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AccountId}.dkr.ecr.us-east-1.amazonaws.com 
      - sam validate --template template.yaml
      - sam build -t template.yaml
  post_build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sam-cli-dionysus-bucket --output-template-file packaged.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name samcli-dionysus-stack --parameter-overrides Env=$MyEnv --capabilities CAPABILITY_IAM
      
 
