version: 0.2

env:
  variables:
    MyEnv: "dev"
    MyAccountId: "548616401217"
    MyRegion: "us-east-1"

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
     #- pip install boto3
     #- sam --version

  build:
    commands:
      - sam validate --template template.yaml
      - sam build -t template.yaml
     #- aws s3 sync resources s3://sam-cli-dionysus-bucket/resources/ --delete

  post_build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sam-cli-dionysus-bucket --output-template-file packaged.yaml --image-repositories ecr-repo.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file template.yaml --stack-name $MyEnv-dionysus-stack --parameter-overrides Env=$MyEnv AccountId=$MyAccountId Region=$MyRegion --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
       
