version: 0.2

env:
  variables:
    MyEnv: "testing"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
      
  build:
    commands:
      - sam validate --template template_sam.yaml
      - sam build -t template_sam.yaml
  post_build:
    commands:
      - sam package --template-file template_sam.yaml --s3-bucket samcli-python-bucket --output-template-file packaged.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name dev-dionysus-stack --parameter-overrides Env=$MyEnv --capabilities CAPABILITY_IAM
      
 
