version: 0.2

env:
  variables:
    MyEnv: "dev"
    MyAccountId: "548616401217"
    MyRegion: "us-east-1"

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
     #- pip install boto3
     #- sam --version

  build:
    commands:
      - sam validate --template template.yaml
      - sam build --use-container -t template.yaml
     # - aws ecr get-login-password --region $MyRegion | docker login --username AWS --password-stdin $MyAccountId.dkr.ecr.us-east-1.amazonaws.com 
     #- aws s3 sync resources s3://sam-cli-dionysus-bucket/resources/ --delete

  post_build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sam-cli-dionysus-bucket --output-template-file packaged.yaml --image-repositories MyLambdaFunction2=548616401217.dkr.ecr.us-east-1.amazonaws.com/test MyLambdaFunction3=548616401217.dkr.ecr.us-east-1.amazonaws.com/test
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file template.yaml --stack-name $MyEnv-dionysus-stack - --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides Env=$MyEnv AccountId=$MyAccountId Region=$MyRegion --image-repositories MyLambdaFunction2=548616401217.dkr.ecr.us-east-1.amazonaws.com/test MyLambdaFunction3=548616401217.dkr.ecr.us-east-1.amazonaws.com/test
