version = 0.1
[default]
[default.deploy]
[default.package]

[default.package.options]
image_repository = "548616401217.dkr.ecr.us-east-1.amazonaws.com/test"
imageRepository = "548616401217.dkr.ecr.us-east-1.amazonaws.com/check-gmail-api"

[default.deploy.image_repositories]
image_repository = "548616401217.dkr.ecr.us-east-1.amazonaws.com/test"
imageRepository = "548616401217.dkr.ecr.us-east-1.amazonaws.com/check-gmail-api"


