AWSTemplateFormatVersion: '2010-09-09'
#Transform: AWS::Serverless-2016-10-31
Parameters:
  Region:
    Type: String
    Default: us-east-1
    Description: The AWS region in which to create resources.

  AccountId:
    Type: String
    Default: 548616401217
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    #Default: dev
    Description: Environment name.

Resources:
  user-api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: resources/user-api.yml
      Parameters: 
        Region: !Ref Region
        AccountId: !Ref AccountId
        Env: !Ref Env
    
      
