
AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Hello from Lambda!'
              }
      Handler: index.lambda_handler
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.8
 
 
  MyRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: MyRestApi
  MyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyRestApi
      ParentId: !GetAtt MyRestApi.RootResourceId
      PathPart: 'hello'
  MyMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref MyRestApi
      ResourceId: !Ref MyResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:548616401217:function:test-function/invocations'
  MyDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - MyMethod
    Properties:
      RestApiId: !Ref MyRestApi
  MyStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref MyRestApi
      DeploymentId: !Ref MyDeployment
      StageName: prod
      
Outputs:
  ApiEndpoint:
    Description: 'API endpoint URL'
    Value: !Sub 'https://test-api.execute-api.us-east-1.amazonaws.com/prod/hello'
