AWSTemplateFormatVersion: '2010-09-09'
#Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Region:
    Type: String
    Description: The AWS region in which to create resources.
    Default: us-east-1

  AccountId:
    Type: String
    Description: The AWS account ID where the resources will be created.
    Default: 548616401217
      
  Env:
    Type: String
    Description: Environment name.
    Default: testing
    
Resources:
  MyLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: MyLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MyLambdaFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${Env}-user-api-1'
      Handler: user-api/lambda_function.lambda_handler
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.9
      Environment:
        Variables:
          env: !Sub '${Env}'
